version: '3.8'
services:
  jupyterlab:
    image: glcr.b-data.ch/jupyterlab/cuda/julia/base
    stdin_open: true
    tty: true
    user: root
    restart: unless-stopped
    volumes: 
    - ../src:/home/jovyan/projects
    ports: 
      - 8888:8888
    environment:
      JUPYTER_TOKEN: "Test1234!"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]